### ISSUE TITLE
您好，有个问题想请教一下！

### ISSUE THREAD

**Issue by hitsz-zuoqi** [HymEric/VSR-DUF-Reimplement#11]
```
for r in range(3, 6):
    t = BatchNorm(x, is_train, name='Rbn' + str(r + 1) + 'a')
    t = tf.nn.relu(t)
    t = Conv3D(t, [1, 1, 1, F, F], [1, 1, 1, 1, 1], 'VALID', name='Rconv' + str(r + 1) + 'a')

    t = BatchNorm(t, is_train, name='Rbn' + str(r + 1) + 'b')
    t = tf.nn.relu(t)
    t = Conv3D(tf.pad(t, sp, mode='CONSTANT'), [3, 3, 3, F, G], [1, 1, 1, 1, 1], 'VALID',
               name='Rconv' + str(r + 1) + 'b')

    x = tf.concat([x[:, 1:-1], t], 4)
    F += G
```

是这样的，我发现在DUF的implemention里面，最后三层的denseNet好像有去掉一个channel，我不确定这是去掉原始RGB的channel还是什么？？？
而且我通读了论文也没有发现有类似的说明，请问您知道为什么要这么做嘛？

**Comment by akash-yadagouda** [comment]
This is the case. I found that in the implementation of DUF, the last three layers of denseNet seem to have a channel removed. I'm not sure if this is the original RGB channel or what? ? ?
And I have read through the paper and found no similar explanation. Do you know why you want to do this?

English version of the above comment

**Comment by hitsz-zuoqi** [comment]
> This is the case. I found that in the implementation of DUF, the last three layers of denseNet seem to have a channel removed. I'm not sure if this is the original RGB channel or what? ? ?
> And I have read through the paper and found no similar explanation. Do you know why you want to do this?
> 
> English version of the above comment

Hey,I have been reading through the code and I find that the input is in fact 7 frames
And thus the input is a tensor with shape [1,3,7,H,W]
Each time the operation x[:, 1:-1] will make the depth(initially as 7) decline by 2
After 3 iteration the shape of the output will be [1,3,1,H,W]
I think this is acting as an operation to fuse the information from all 7 frames~
