### ISSUE TITLE
About input image size

### ISSUE THREAD

**Issue by LI945** [HymEric/VSR-DUF-Reimplement#6]
First thanks for the code

When the input image is 5:4, it works perfectly, but when the input image is 16:9, t = Conv3D(tf.pad(t, STP, mode='CONSTANT'), [3, 3, 3, F, G], [1, 1, 1, 1, 1], ' Name ='Rconv' + STR (r + 1) + 'b')  on line 152 of my_train error, do you know how to solve it?

Thank you very much!

**Comment by HymEric** [comment]
Do you say 5:4 or 16:9 is the  Weight:Height of training images?
