### ISSUE TITLE
residual is always zero

### ISSUE THREAD

**Issue by yueyilia** [HymEric/VSR-DUF-Reimplement#7]
filter | residual | sr | hr
![1](https://user-images.githubusercontent.com/39787440/60478759-2d546f80-9cb6-11e9-9662-2fc8a0cbe965.png)

**Comment by HymEric** [comment]
Sorry, I haven't visualize or check residual value. I will check in few days later. Could you tell me your training strategy?

**Comment by yueyilia** [comment]
I found the reason that I used sgd optimizer rather than adam. After I use adam, it works.
But the results is far below my expectation. Have you trained a good model?

**Comment by HymEric** [comment]
Yeal, different optimizer sometimes gives us somewhat large difference. I haven't trained a good model to perform as paper's. But I will continue this work if I have time in the future. Thanks for your attention.
