### ISSUE TITLE
you haven't used h which is returned from gkern further.Also the DownSample function which is there in the author's code.

### ISSUE THREAD

**Issue by arnabmaity** [HymEric/VSR-DUF-Reimplement#8]
In mytrain.py after line 128, h is not used any further.
h = gkern(13, 1.6)  # 13 and 1.6 for x4
h = h[:, :, np.newaxis, np.newaxis].astype(np.float32)
so is it not downsampled as there in the author's code?

**Comment by HymEric** [comment]
I'm sorry for replying so late.
Yes. I don't use it because I have got the LR images before training in the dataset preparation. This means we have the LR and HR folder where to save the training image piars. See [README](https://github.com/HymEric/VSR-DUF-Reimplement) for more details.
